### ISSUE TITLE
Exception logging

### ISSUE THREAD

**Issue by RobinPeensVelocity** [markmcdowell/NLog.Targets.ElasticSearch#127]
Found an issue where certain fields on Exceptions cause NLog internal exceptions and never make it to elastic as a result... I have proposed a solution on the following PR : https://github.com/markmcdowell/NLog.Targets.ElasticSearch/pull/126

2020-06-10 15:35:53.7916 Warn Error serializing exception property 'ScopeId', property ignored Exception: Newtonsoft.Json.JsonSerializationException: Error getting value from 'ScopeId' on 'System.Net.IPAddress'. ---> System.Net.Sockets.SocketException: The attempted operation is not supported for the type of object referenced
   at System.Net.IPAddress.get_ScopeId()
   at lambda_method(Closure , Object )
   at Newtonsoft.Json.Serialization.ExpressionValueProvider.GetValue(Object target)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Serialization.ExpressionValueProvider.GetValue(Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CalculatePropertyValues(JsonWriter writer, Object value, JsonContainerContract contract, JsonProperty member, JsonProperty property, JsonContract& memberContract, Object& memberValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)

**Comment by RobinPeensVelocity** [comment]
That's great and more configurable thanks
