### ISSUE TITLE
Exception in ElasticSearch for NLog.Level = Error

### ISSUE THREAD

**Issue by sygnowskip** [markmcdowell/NLog.Targets.ElasticSearch#64]
Hi,
I have some problems with integration with elasticsearch.

I'm using (on OSX):
ASP.NET Core 2.0 application (NLog@4.5.3, NLog.Web.AspNetCore@4.5.2, NLog.Targets.ElasticSearch@5.0.0) - https://github.com/sygnowskip/elastic-search-example

ElasticSearch: Version: 6.2.3, Build: c59ff00/2018-03-13T10:06:29.741383Z, JVM: 1.8.0_121

What is the problem?
When I try to log error to elasticsearch, after exception in my example application, elasticsearch is throwing an exception:

> [DEBUG][o.e.a.b.TransportShardBulkAction] [logstash-2018.04.18][4] failed to execute bulk item (index) BulkShardRequest [[logstash-2018.04.18][4]] containing [2] requests
java.lang.IllegalArgumentException: mapper [exception.TargetSite.CustomAttributes.Constructor.Module.Assembly.CustomAttributes.Constructor.Module.Assembly.CustomAttributes.ConstructorArguments.Value] of different type, current_type [long], merged_type [text]
	at org.elasticsearch.index.mapper.FieldMapper.doMerge(FieldMapper.java:354) ~[elasticsearch-6.2.3.jar:6.2.3]
	at org.elasticsearch.index.mapper.NumberFieldMapper.doMerge(NumberFieldMapper.java:1038) ~[elasticsearch-6.2.3.jar:6.2.3]
	at org.elasticsearch.index.mapper.FieldMapper.merge(FieldMapper.java:340) ~[elasticsearch-6.2.3.jar:6.2.3]
	at org.elasticsearch.index.mapper.FieldMapper.merge(FieldMapper.java:52) ~[elasticsearch-6.2.3.jar:6.2.3]
	at org.elasticsearch.index.mapper.DocumentParser.createDynamicUpdate(DocumentParser.java:221) ~[elasticsearch-6.2.3.jar:6.2.3]
	at org.elasticsearch.index.mapper.DocumentParser.parseDocument(DocumentParser.java:79) ~[elasticsearch-6.2.3.jar:6.2.3]
	at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:261) ~[elasticsearch-6.2.3.jar:6.2.3]
	at org.elasticsearch.index.shard.IndexShard.prepareIndex(IndexShard.java:714) ~[elasticsearch-6.2.3.jar:6.2.3]
	at org.elasticsearch.index.shard.IndexShard.applyIndexOperation(IndexShard.java:692) ~[elasticsearch-6.2.3.jar:6.2.3]
	at org.elasticsearch.index.shard.IndexShard.applyIndexOperationOnPrimary(IndexShard.java:673) ~[elasticsearch-6.2.3.jar:6.2.3]
	at org.elasticsearch.action.bulk.TransportShardBulkAction.executeIndexRequestOnPrimary(TransportShardBulkAction.java:548) ~[elasticsearch-6.2.3.jar:6.2.3]
	at org.elasticsearch.action.bulk.TransportShardBulkAction.executeIndexRequest(TransportShardBulkAction.java:140) [elasticsearch-6.2.3.jar:6.2.3]
	at org.elasticsearch.action.bulk.TransportShardBulkAction.executeBulkItemRequest(TransportShardBulkAction.java:236) [elasticsearch-6.2.3.jar:6.2.3]
	at org.elasticsearch.action.bulk.TransportShardBulkAction.performOnPrimary(TransportShardBulkAction.java:123) [elasticsearch-6.2.3.jar:6.2.3]
	at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:110) [elasticsearch-6.2.3.jar:6.2.3]
	at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:72) [elasticsearch-6.2.3.jar:6.2.3]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryShardReference.perform(TransportReplicationAction.java:1034) [elasticsearch-6.2.3.jar:6.2.3]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryShardReference.perform(TransportReplicationAction.java:1012) [elasticsearch-6.2.3.jar:6.2.3]
	at org.elasticsearch.action.support.replication.ReplicationOperation.execute(ReplicationOperation.java:103) [elasticsearch-6.2.3.jar:6.2.3]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.onResponse(TransportReplicationAction.java:359) [elasticsearch-6.2.3.jar:6.2.3]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.onResponse(TransportReplicationAction.java:299) [elasticsearch-6.2.3.jar:6.2.3]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$1.onResponse(TransportReplicationAction.java:975) [elasticsearch-6.2.3.jar:6.2.3]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$1.onResponse(TransportReplicationAction.java:972) [elasticsearch-6.2.3.jar:6.2.3]
	at org.elasticsearch.index.shard.IndexShardOperationPermits.acquire(IndexShardOperationPermits.java:238) [elasticsearch-6.2.3.jar:6.2.3]
	at org.elasticsearch.index.shard.IndexShard.acquirePrimaryOperationPermit(IndexShard.java:2221) [elasticsearch-6.2.3.jar:6.2.3]
	at org.elasticsearch.action.support.replication.TransportReplicationAction.acquirePrimaryShardReference(TransportReplicationAction.java:984) [elasticsearch-6.2.3.jar:6.2.3]
	at org.elasticsearch.action.support.replication.TransportReplicationAction.access$500(TransportReplicationAction.java:98) [elasticsearch-6.2.3.jar:6.2.3]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.doRun(TransportReplicationAction.java:320) [elasticsearch-6.2.3.jar:6.2.3]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-6.2.3.jar:6.2.3]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:295) [elasticsearch-6.2.3.jar:6.2.3]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:282) [elasticsearch-6.2.3.jar:6.2.3]
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:66) [elasticsearch-6.2.3.jar:6.2.3]
	at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:656) [elasticsearch-6.2.3.jar:6.2.3]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:672) [elasticsearch-6.2.3.jar:6.2.3]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-6.2.3.jar:6.2.3]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]

This problem is only for logging errors (NLog LogLevel = Error), for testing purposes I'm logging this errors also to txt files (in /Logs directory).

How to reproduce?
1. Download my example application
2. Go to url http://localhost/api/values/1
3. Verify in ElasticSearch, that trace is correctly sent to them, e.g.: http://localhost:9200/logstash-2018.04.18/_search
4. Go to url http://localhost/api/values, I'm throwing NullReferenceException for testing purposes
5. Take a look on elasticsearch console, exception occured
6. Verify in ElasticSearch, that errors are not logged, e.g.: http://localhost:9200/logstash-2018.04.18/_search

Could you help me? How can I fix it?

**Comment by markmcdowell** [comment]
@sygnowskip could you try on [6.0.0](https://github.com/markmcdowell/NLog.Targets.ElasticSearch/releases/tag/6.0.0) it's using a newer version of the elasticsearch api.

**Comment by sygnowskip** [comment]
@markmcdowell I had this problem so long ago, since then I've changed the approach to sending logs to elasticsearch 😃 

So, we could close this issue
