### ISSUE TITLE
Nullreference exception

### ISSUE THREAD

**Issue by Baklap4** [markmcdowell/NLog.Targets.ElasticSearch#77]
Heeey while moving our logging to the cloud we jumped upon an error:
`2018-12-04 15:28:57.4550 Error Error while sending log messages to elasticsearch: message="Object reference not set to an instance of an object."`
[InternalsLog.txt](https://github.com/markmcdowell/NLog.Targets.ElasticSearch/files/2644426/InternalsLog.txt)

Our nlog.config looks like this
```
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      autoReload="true"
      internalLogLevel="Debug"
      internalLogToConsoleError="true">

  <extensions>
    <add assembly="NLog.Targets.ElasticSearch"/>
  </extensions>

  <targets>
    <target name="ElasticWrapper" xsi:type="BufferingWrapper" bufferSize="2000" flushTimeout="30000">
      <target name="Elastic" xsi:type="ElasticSearch" index="index-${date:format=yyyy.MM.dd}" uri="https://uri.io:9243" requireAuth="true" username="user" password="password">
        <field name="app" layout="${event-properties:item=app}" />
        <field name="contextId" layout="${event-properties:item=contextId}" />
        <field name="scope" layout="${event-properties:item=scope}" />
        <field name="origin" layout="${event-properties:item=origin}" />
        <field name="message" layout="${event-properties:item=message}" />
        <field name="stacktrace" layout="${event-properties:item=stacktrace}" />
      </target>
    </target>
    <target name="Console" xsi:type="Console" layout="${longdate} ${callsite} ${level} ${message}"/>
  </targets>

  <rules>
    <logger name="*" minlevel="Debug" writeTo="Console" />
    <logger name="*" minlevel="Debug" writeTo="ElasticWrapper" />
  </rules>
</nlog>
```

My guess is and as shown by fiddler is that there are two requests fired (localhost). First one goes to `/`  and then after a 200 OK do a request to `/_bulk` posting the logs.
Within our cloud we use the users and get a 403 upon the first call to `/` and therefore blocking other requests namely the `/_bulk` call to actually post the results..

**Comment by snakefoot** [comment]
I guess when  #73 is included in some release, then it will be easier to figure out where the "Object reference not set to an instance of an object" comes from.

**Comment by Baklap4** [comment]
If i disable the elasticwrapper and just use the elastic target i'm getting this stacktrace:
```
2018-12-04 16:42:02.1936 Error Error while sending log messages to elasticsearch: message="Object reference not set to an instance of an object."
2018-12-04 16:42:02.2487 Error Exception in asynchronous handler. Exception: NLog.NLogRuntimeException: Exception occurred in NLog ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Elasticsearch.Net.RequestPipeline.CreateClientException[TResponse](TResponse response, IApiCallDetails callDetails, RequestData data, List`1 pipelineExceptions) in c:\Projects\elastic\net-6\src\Elasticsearch.Net\Transport\Pipeline\RequestPipeline.cs:line 502
   at Elasticsearch.Net.Transport`1.FinalizeResponse[TResponse](RequestData requestData, IRequestPipeline pipeline, List`1 seenExceptions, TResponse response) in c:\Projects\elastic\net-6\src\Elasticsearch.Net\Transport\Transport.cs:line 174
   at Elasticsearch.Net.Transport`1.Request[TResponse](HttpMethod method, String path, PostData data, IRequestParameters requestParameters) in c:\Projects\elastic\net-6\src\Elasticsearch.Net\Transport\Transport.cs:line 97
   at Elasticsearch.Net.ElasticLowLevelClient.Bulk[TResponse](PostData body, BulkRequestParameters requestParameters) in c:\Projects\elastic\net-6\src\Elasticsearch.Net\ElasticLowLevelClient.Generated.cs:line 26
   at NLog.Targets.ElasticSearch.ElasticSearchTarget.SendBatch(ICollection`1 logEvents)
   --- End of inner exception stack trace ---
   at NLog.LoggerImpl.<>c__DisplayClass1_0.<Write>b__1(Exception ex)
   at NLog.Internal.SingleCallContinuation.Function(Exception exception)
Application startup exception: System.AggregateException: An error occurred while writing to logger(s). (Exception occurred in NLog) ---> NLog.NLogRuntimeException: Exception occurred in NLog ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Elasticsearch.Net.RequestPipeline.CreateClientException[TResponse](TResponse response, IApiCallDetails callDetails, RequestData data, List`1 pipelineExceptions) in c:\Projects\elastic\net-6\src\Elasticsearch.Net\Transport\Pipeline\RequestPipeline.cs:line 502
   at Elasticsearch.Net.Transport`1.FinalizeResponse[TResponse](RequestData requestData, IRequestPipeline pipeline, List`1 seenExceptions, TResponse response) in c:\Projects\elastic\net-6\src\Elasticsearch.Net\Transport\Transport.cs:line 174
   at Elasticsearch.Net.Transport`1.Request[TResponse](HttpMethod method, String path, PostData data, IRequestParameters requestParameters) in c:\Projects\elastic\net-6\src\Elasticsearch.Net\Transport\Transport.cs:line 97
   at Elasticsearch.Net.ElasticLowLevelClient.Bulk[TResponse](PostData body, BulkRequestParameters requestParameters) in c:\Projects\elastic\net-6\src\Elasticsearch.Net\ElasticLowLevelClient.Generated.cs:line 26
   at NLog.Targets.ElasticSearch.ElasticSearchTarget.SendBatch(ICollection`1 logEvents)
   --- End of inner exception stack trace ---
   at NLog.LoggerImpl.<>c__DisplayClass1_0.<Write>b__1(Exception ex)
   at NLog.Internal.SingleCallContinuation.Function(Exception exception)
   at NLog.Targets.ElasticSearch.ElasticSearchTarget.SendBatch(ICollection`1 logEvents)
   at NLog.Targets.Target.WriteAsyncThreadSafe(AsyncLogEventInfo logEvent)
   at NLog.Targets.Target.WriteAsyncLogEvent(AsyncLogEventInfo logEvent)
   at NLog.LoggerImpl.WriteToTargetWithFilterChain(Target target, FilterResult result, LogEventInfo logEvent, AsyncContinuation onException)
   at NLog.LoggerImpl.Write(Type loggerType, TargetWithFilterChain targets, LogEventInfo logEvent, LogFactory factory)
   at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.Extensions.Logging.Logger`1.Microsoft.Extensions.Logging.ILogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.Extensions.Logging.LoggerMessage.<>c__DisplayClass5_0`1.<Define>b__0(ILogger logger, T1 arg1, Exception exception)
   at Microsoft.Extensions.Logging.LoggingExtensions.UsingProfileAsKeyRepositoryWithDPAPI(ILogger logger, String fullName)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager.GetFallbackKeyRepositoryEncryptorPair()
   at Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager..ctor(IOptions`1 keyManagementOptions, IActivator activator, ILoggerFactory loggerFactory)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitSingleton(SingletonCallSite singletonCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitSingleton(SingletonCallSite singletonCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.DataProtectionServiceCollectionExtensions.<>c.<AddDataProtectionServices>b__2_0(IServiceProvider s)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitSingleton(SingletonCallSite singletonCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitSingleton(SingletonCallSite singletonCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitSingleton(SingletonCallSite singletonCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitSingleton(SingletonCallSite singletonCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitSingleton(SingletonCallSite singletonCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitSingleton(SingletonCallSite singletonCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitTransient(TransientCallSite transientCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
---> (Inner Exception #0) NLog.NLogRuntimeException: Exception occurred in NLog ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Elasticsearch.Net.RequestPipeline.CreateClientException[TResponse](TResponse response, IApiCallDetails callDetails, RequestData data, List`1 pipelineExceptions) in c:\Projects\elastic\net-6\src\Elasticsearch.Net\Transport\Pipeline\RequestPipeline.cs:line 502
   at Elasticsearch.Net.Transport`1.FinalizeResponse[TResponse](RequestData requestData, IRequestPipeline pipeline, List`1 seenExceptions, TResponse response) in c:\Projects\elastic\net-6\src\Elasticsearch.Net\Transport\Transport.cs:line 174
   at Elasticsearch.Net.Transport`1.Request[TResponse](HttpMethod method, String path, PostData data, IRequestParameters requestParameters) in c:\Projects\elastic\net-6\src\Elasticsearch.Net\Transport\Transport.cs:line 97
   at Elasticsearch.Net.ElasticLowLevelClient.Bulk[TResponse](PostData body, BulkRequestParameters requestParameters) in c:\Projects\elastic\net-6\src\Elasticsearch.Net\ElasticLowLevelClient.Generated.cs:line 26
   at NLog.Targets.ElasticSearch.ElasticSearchTarget.SendBatch(ICollection`1 logEvents)
   --- End of inner exception stack trace ---
   at NLog.LoggerImpl.<>c__DisplayClass1_0.<Write>b__1(Exception ex)
   at NLog.Internal.SingleCallContinuation.Function(Exception exception)
   at NLog.Targets.ElasticSearch.ElasticSearchTarget.SendBatch(ICollection`1 logEvents)
   at NLog.Targets.Target.WriteAsyncThreadSafe(AsyncLogEventInfo logEvent)
   at NLog.Targets.Target.WriteAsyncLogEvent(AsyncLogEventInfo logEvent)
   at NLog.LoggerImpl.WriteToTargetWithFilterChain(Target target, FilterResult result, LogEventInfo logEvent, AsyncContinuation onException)
   at NLog.LoggerImpl.Write(Type loggerType, TargetWithFilterChain targets, LogEventInfo logEvent, LogFactory factory)
   at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)<---

2018-12-04 16:42:02.2714 Microsoft.AspNetCore.Hosting.Internal.HostingLoggerExtensions.ApplicationError Fatal Application startup exception
2018-12-04 16:42:02.3490 Error Error while sending log messages to elasticsearch: message="Object reference not set to an instance of an object."
2018-12-04 16:42:02.3490 Error Exception in asynchronous handler. Exception: NLog.NLogRuntimeException: Exception occurred in NLog ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Elasticsearch.Net.RequestPipeline.CreateClientException[TResponse](TResponse response, IApiCallDetails callDetails, RequestData data, List`1 pipelineExceptions) in c:\Projects\elastic\net-6\src\Elasticsearch.Net\Transport\Pipeline\RequestPipeline.cs:line 502
   at Elasticsearch.Net.Transport`1.FinalizeResponse[TResponse](RequestData requestData, IRequestPipeline pipeline, List`1 seenExceptions, TResponse response) in c:\Projects\elastic\net-6\src\Elasticsearch.Net\Transport\Transport.cs:line 174
   at Elasticsearch.Net.Transport`1.Request[TResponse](HttpMethod method, String path, PostData data, IRequestParameters requestParameters) in c:\Projects\elastic\net-6\src\Elasticsearch.Net\Transport\Transport.cs:line 97
   at Elasticsearch.Net.ElasticLowLevelClient.Bulk[TResponse](PostData body, BulkRequestParameters requestParameters) in c:\Projects\elastic\net-6\src\Elasticsearch.Net\ElasticLowLevelClient.Generated.cs:line 26
   at NLog.Targets.ElasticSearch.ElasticSearchTarget.SendBatch(ICollection`1 logEvents)
   --- End of inner exception stack trace ---
   at NLog.LoggerImpl.<>c__DisplayClass1_0.<Write>b__1(Exception ex)
   at NLog.Internal.SingleCallContinuation.Function(Exception exception)
```

**Comment by snakefoot** [comment]
Looks like you are missing this fix: https://github.com/elastic/elasticsearch-net/pull/3101

Try upgrading to https://www.nuget.org/packages/Elasticsearch.Net/6.1.0 (or newer)

**Comment by Baklap4** [comment]
Upgrading to 6.1.0 resolves the nullreference however does not get the log to work properly.
I'm now as suspecting getting a 403 while pinging Elastic search.

`2018-12-05 08:56:48.4196 Error Failed to send log messages to elasticsearch: status=403, message="One or more errors occurred. (Failed to ping the specified node.)"`

**Comment by snakefoot** [comment]
Created #76 that adds support for setting DisablePing on the NLog target.

**Comment by Baklap4** [comment]
i'll close this issue since #76 and https://github.com/markmcdowell/NLog.Targets.ElasticSearch/pull/76/commits/d27d12b91e617d1bc21e8a6fd19f836501f3c697 fixed it thanks! <3
